version: '3.8'

services:
  flights:
    build:
      context: ./flights_microservice
    ports:
      - "9055:9055"
    container_name: flights_service

  tickets:
    build:
      context: ./tickets_microservice
    ports:
      - "9056:9056"
    container_name: tickets_service
